import type { Metadata } from "next";
import { Lato } from 'next/font/google'
import '@/shared/style/global.scss'

const lato = Lato({
  subsets: ['latin'],
  weight: '400',
  style: "normal",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={lato.className}>
      <body>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
